### ISSUE TITLE
Can't install Keras?

### ISSUE THREAD

**Issue by benlaurie** [jrmarino/synth#121] opened 2018-02-27 13:00 UTC
Fresh install of synth, I do:

`$ synth install math/py-keras@py36`

which appears to work, then ends up with:

```Synth repository update completed. 1114 packages processed.
All repositories are up to date.
Updating database digests format: 100%
pkg: No packages available to install matching 'py36-keras-2.1.4' have been found in the repositories
Unfortunately, the system upgraded failed.
```

**Comment by jrmarino** [comment] 2018-02-27 13:07
take synth out of the equation.
- use pkg(8) to install directly (the repository should already be generated but you can regenerate it with synth too)
- check the package repository directory for the actual package name

Did you check the port makefile to see if it excludes py36 flavor specifically?

**Comment by jrmarino** [comment] 2018-02-27 13:09
FYI, the primary function of synth is to build packages and assembly repositories.  The "upgrade / install" commands are just wrappers to pkg(8).  Sometimes pkg(8) gives back bad data because it has old packages installed.  You don't need to use "synth install" at all.

**Comment by benlaurie** [comment] 2018-02-28 21:31
Right, I was trying to build keras. Anyway, the problem appears to be dependencies that synth declined to build:

```
-=>  Chronology of last build  <=-
Started: Wednesday, 28 FEB 2018 at 21:27:35 UTC
Ports to build: 35

Purging any ignored/broken ports first ...
00:00:02 math/openblas has been ignored: has to be built manually: Optimizes for the build machine.
           Skipped: math/py-numpy@py36
           Skipped: math/suitesparse
           Skipped: science/py-scipy@py36
           Skipped: math/py-theano@py36
           Skipped: math/py-keras@py36
00:00:02 math/atlas has been ignored: has to be built manually: Optimizes for the local machine.
00:00:02 Sanity check complete. Ports remaining to build: 0
Finished: Wednesday, 28 FEB 2018 at 21:27:37 UTC
Duration: 00:00:02

---------------------------
--  Final Statistics
---------------------------
 Initial queue size: 7
     packages built: 0
            ignored: 2
            skipped: 5
             failed: 0
```

which I found in /var/log/synth. But synth itself doesn't give much clue to a n00b:

```
# synth install math/py-keras@py36
Scanning existing packages.
After inspection, it has been determined that there are no packages that
require rebuilding; the task is therefore complete.
Stand by, recursively scanning 1 port serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100%    264 B   0.3kB/s    00:01    
Fetching packagesite.txz: 100%  266 KiB 272.2kB/s    00:01    
Processing entries: 100%
Synth repository update completed. 1114 packages processed.
All repositories are up to date.
pkg: No packages available to install matching 'py36-keras-2.1.4' have been found in the repositories
Unfortunately, the system upgraded failed.
```

Might be helpful to show that report? Or at least the things that need manual building?

**Comment by jrmarino** [comment] 2018-02-28 21:52
The log is very explicitly telling what the problem is.
Tracing the requirements, py-keras requires py-theano which requires py-numpy.
Your py-numpy has non-default options selecting openblas and atlas, both of which are not allowed to be built as a package.  (incidentally, I raised this scenario as an issue in the mailing list and was run off).

If you don't need atlas and openblas, I suggest you change the py-numpy options.
If you do, you need to modify the makefiles to remove those restrictions on building in a package builder.

**Comment by jrmarino** [comment] 2018-02-28 21:54
better solution: on openblas, you must have customized the options.  You have DYNAMIC_ARCH set on when it's off by default.  Turn it off again.  That's your problem with openblas.

**Comment by benlaurie** [comment] 2018-02-28 21:55
Sorry, what I was getting at is it was not clear there was a log with more information - I found it today, so I now know where to look, but at the time, the only diagnostics I could see was the output of synth, which didn't give much clue what had gone wrong...

**Comment by jrmarino** [comment] 2018-02-28 21:56
atlas can't be fixed with options.  You could modify the makefile to remove this line:

> MANUAL_PACKAGE_BUILD=   Optimizes for the local machine.

**Comment by jrmarino** [comment] 2018-02-28 21:58
yes, the "install" convenience command probably shouldn't fire if any of the build is unsuccessful.  That could be misleading.

**Comment by benlaurie** [comment] 2018-02-28 21:59
openblas doesn't have DYNAMIC_ARCH set on, btw.

**Comment by jrmarino** [comment] 2018-02-28 22:01
sorry, you need to turn it ON then.  I misread the makefile.

**Closed** 2018-05-08 15:58 UTC
