### ISSUE TITLE
Not enough debug and documentation for 06_obsolete_packages.log

### ISSUE THREAD

**Issue by nuclight** [jrmarino/synth#185] opened 2021-03-05 00:43 UTC
Hi, I'm from #183 for which I wrote script to gather more precise dependencies for `/etc/make.conf` and put those to synth.

But strangely, it wants to rebuild almost everything, giving many failed packages, while those packages exist both in Synth's LiveSystem repo and FreeBSD repo. I tried `export WHYFAIL=1` but this did not help much.

First of all, it always starts with
```
Installed package ignored, multimedia/audacious package unmatched
Installed package ignored, multimedia/audacious-plugins package unmatched
Installed package ignored, graphics/py-cairo package unmatched
Installed package ignored, missing from ports: graphics/py-gimp
Installed package ignored, missing from ports: devel/py-gobject
Installed package ignored, missing from ports: x11-toolkits/py-gtk2
Installed package ignored, missing from ports: devel/vulkan-headers
Stand by, comparing installed packages against the ports tree.
```
which I don't understand - why ignored? What is "unmatched" ?

Then, it goes
```
vlc-3.0.11_9,4.txz has less options than required (77)
vlc-3.0.11_9,4.txz failed option check.
lang/python37 package has less dependencies than the port requires (4)
Query: devel/gettext-runtime:gettext-runtime-0.21
devel/libffi:libffi-3.3_1
devel/readline:readline-8.0.4

python37-3.7.9_1.txz failed dependency check.
devel/py-setuptools@py37 package depends on python37-3.7.9_1.txz which doesn't exist or has been scheduled for deletion
py37-setuptools-44.0.0.txz failed dependency check.
devel/ninja package depends on python37-3.7.9_1.txz which doesn't exist or has been scheduled for deletion
...
graphics/graphviz package depends on pango-1.42.4_5.txz which doesn't exist or has been scheduled for deletion
```
So, _which_ options? _Which_ dependencies?

And if I do e.g. `pkg search ^pango-`, it 
```
pango-1.42.4_5                 Open-source framework for the layout and rendering of i18n text
pango-1.42.4_5                 Open-source framework for the layout and rendering of i18n text
```
and `synth/live_packages/All/pango-1.42.4_5.txz` exists, and all of a few which I checked by hand - exists there, too!

I thought that FreeBSD repo may have been changed for a week (I sit on quarterly branch though) and tried to `svn up` ports tree. No effect.

What I suspect, however, is may be some database corruption?

If I try to go install some "few-deps" port, e.g.
`cd /usr/ports/ports-mgmt/pkg_tree && make missing`
I see empty output, which I think means all deps are already installed.

But if I try install it, I get
```
$ pkg install pkg_tree
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating Synth repository catalogue...
Synth repository is up to date.
All repositories are up to date.
Updating database digests format: 100%
The following 19 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        Box2D: 2.3.1 [Synth]
        blas: 3.5.0_6 [FreeBSD]
        c-ares: 1.16.1 [Synth]
        compat10x-amd64: 10.4.1004000.20181014 [FreeBSD]
        double-conversion: 3.1.5.19 [FreeBSD]
        freealut: 1.1.0_4 [Synth]
        lame: 3.100_2 [FreeBSD]
        lapack: 3.5.0_8 [FreeBSD]
        libde265: 1.0.2_5 [Synth]
        libpcap: 1.9.1_1 [Synth]
        libpsl: 0.21.1_1 [FreeBSD]
        librsvg2-rust: 2.50.2 [FreeBSD]
        libssh: 0.9.5 [Synth]
        openblas: 0.3.12,1 [FreeBSD]
        openldap-sasl-client: 2.4.57 [FreeBSD]
        openssl: 1.1.1j,1 [Synth]
        perl5.30: 5.30.3_1 [FreeBSD]
        pkg_tree: 1.1_4 [FreeBSD]
        webrtc-audio-processing0: 0.3.1_2 [FreeBSD]

Number of packages to be installed: 19

The process will require 229 MiB more space.
37 MiB to be downloaded.
```
and if I try to install some other pkg, this strange list is presented to me again!

**Comment by jrmarino** [comment] 2021-03-05 02:26
"unmatched" and "missing" basically means the package names have changed, which means the packages have been installed for a long, long time and the ports tree evolved past them.
In cases like that, the best thing to do is make a list of ports you want on the system, remove all packages and install those top level ports.  Most of your problems stem from ports tree changes.

as to "which options" it's irrelevant.  The options have to match perfectly.  If they don't, it doesn't really matter which option is missing or extra.  It's just a consequence of the port makefile changing and differing from when the package you have installed was built.

As to "which dependencies" you have to deduce it.  You get a listing of the ones the installed package has.  You need make directives like "make -V LIB_DEPENDS -V RUN_DEPENDS" (not sure if that's exactly correct but you get the idea) to figure out what the current port makefile is doing. 

Yes, most of these are caused by the ever changing ports tree.
Problems like this is why I created www.ravenports.com which solves stuff like that.

I highly doubt there is any database corruption.

**Comment by nuclight** [comment] 2021-03-05 21:20
Well, for "multimedia/audacious package unmatched" I've found it - package renamed to -gtk2 suffix, origin stays the same.

But for `pango-1.42.4_5.txz which doesn't exist or has been scheduled for deletion` question is still open: `pkg fetch -U -r FreeBSD pango-1.42.4_5` works perfectly fine, so why Synth says so?

>  If they don't, it doesn't really matter which option is missing or extra

Not so, if i know which option then I can go to `make config` and decide by weighting it whether I need this option or not, then act so.

> As to "which dependencies" you have to deduce it. You get a listing of the ones the installed package has. You need make directives like "make -V LIB_DEPENDS -V RUN_DEPENDS" (not sure if that's exactly correct but you get the idea) to figure out what the current port makefile is doing.

As for now, I'm forced to figure what Synth is doing and for why. Thus this ticket. I can't use `gdb` for it. I tried `ktrace -di synth status` only to find that arguments to `execve()` are not displayed :( I made a shell wrapper for `pkg` logging it's `$@` and stdout but this became scrambled a little due to parallel execution. I fear that if I make such wrapper for `make` I'll be drowned in tons of it's recursive calls :-/ while still I'm not confident with make/ports and what to do with them and what directives I really need.

Finally, even getting output from ports/pkg by wrapping their utilities still won't tell me what Synth do with their output and why it makes it's decisions.

Please help.

As for database, I looked at https://pkg-status.freebsd.org/builds?jailname=114amd64 and see there only 1979 queued and  190 built packages for March, 04 - may be problem is there? I don't know how to read that site properly. Just I know that a week ago Synth offered much more reasonable package list.
BTW, I even tried to delete it's live system repo to try from scratch and it said "No packages qualify for prefetching"...
And I'm on "quarterly" branch which surely have very little changes for period of just a week...

**Comment by jrmarino** [comment] 2021-03-05 21:38
you're not really explaining why aren't taking the approach of building a repository with a top-level list, removing all packages, and reinstalling them from the repository.  Trying to diagnose all these problems seems like totally unnecessary work.

for pango, I'd need to see the entire log.  It may have been invalidated for some reason (maybe a dependency, maybe an option change) and thus scheduled for deletion.

This kind of "help me understand why" is really out of scope.  I'm only supporting synth on a bug basis.  FreeBSD doesn't even have the latest release the last time I looked.

On top of that, the whole "use packages from FreeBSD repository" was always advertised as a "I don't recommend - your mileage may vary -- use at your own risk" feature.  The differences between ports trees always has the potential to present problems. 

I'm not even sure why you are mentioning ktrace and gdb -- you're framing this as if you think this behavior is actually a bug.

**Comment by nuclight** [comment] 2021-03-05 21:59
> you're not really explaining why aren't taking the approach of building a repository with a top-level list, removing all packages, and reinstalling them from the repository. Trying to diagnose all these problems seems like totally unnecessary work.

As I mentioned in #183 I'm trying to solve the problem with "11.4 openssl from ports" on old i3 machine with only 12G of RAM. For example, www/chromium just won't build on it - not enough resources. I just can't afford it :( For Firefox and others, well, may be their build will not fail but also takes very long.

> for pango, I'd need to see the entire log. It may have been invalidated for some reason (maybe a dependency, maybe an option change) and thus scheduled for deletion.

Which log should I attach? This happens already on `synth status`. For pango, it just one of examples, it says like these to python, and to perl, and to many other packages...

> FreeBSD doesn't even have the latest release the last time I looked.

Should I read this as "get a compiler and compile from git" ? This is a machine with obsoleted (summer) packages which I try to make fresh, so I tried to minimize new ports installing and took existing synth package.

> use at your own risk" feature. The differences between ports trees always has the potential to present problems.

To mitigate this as much as possible, I using `quarterly` branch - it changes little.

> you're framing this as if you think this behavior is actually a bug.

Yes, because these "doesn't exist or scheduled for deletion" - doesn't exist _where_? Scheduled by _whom_? `pkg search` and `pkg fetch` tell that it definitely exists, even two of them - both FreeBSD's and own Synth's repo. Scheduled by upstream ports tree? Not so, the origin port exists and not deprecated, too.

At the very least, this is a bug in messaging and/or documentation, if not code. Synth need somewhat like verbose/debug/trace log levels mode, to help in diagnosing problems.

**Comment by jrmarino** [comment] 2021-03-05 22:23
I was talking about the 06-obsolete log.  It would have mentioned pango earlier.
My point about "Not latest version" was just that nobody cares enough to ask the listed maintainer to update to the latest version.  The changes aren't critical.  No, you don't need to compile the latest.
If the freebsd packages also come from Quarterly, then yes, it would be mitigated.  I don't follow freebsd packaging anymore so I don't know about this.

"scheduled for deletion" -- synth will delete the local package unless you're checking via "status" command.  Synth is logging that if the package exists it is considered invalid, that package will be deleted, and then synth will have to rebuild it.

"doesn't exist" means the package file isn't in the local packages directory.
These are not errors.  It's just saying that either the package doesn't exist, or that it does exist but it's considered invalidate and will be deleted (the equivalent of doesn't exist).
Not a bug.  It's just giving insight into the sanity checking.

**Comment by nuclight** [comment] 2021-03-05 22:56
Well, then this info in your comment must be at least documented in man page.

> If the freebsd packages also come from Quarterly, then yes, it would be mitigated

Yes, I put a branch from ports SVN which is also quarterly, though it can be not always exact revision from which last official repo edition was built... but diff is usually small.

Here is synth's log:
[06_obsolete_packages.log](https://github.com/jrmarino/synth/files/6093993/06_obsolete_packages.log)

I also provided info on first four packages from this 06.log at new comment https://github.com/jrmarino/synth/issues/183#issuecomment-791765775 - from synth's pkg query and Makefiles.

**Closed** 2021-04-05 22:52 UTC
