### ISSUE TITLE
sysnt purge-distfiles can remove all distfiles when error encountered.

### ISSUE THREAD

**Issue by richterb1** [jrmarino/synth#41] opened 2016-03-05 23:58 UTC
Much seems  to depend on what directory you start synth in.

# synth purge-distfiles 
Scanning the distinfo file of every port in the tree ... done
purge_distfiles: Unknown error - directory search
Deleting distfiles/bash/bash43-014
Deleting distfiles/bash/bash43-015
Deleting distfiles/DBI-1.634.tar.gz
....

#cd  /usr/ports
# synth purge-distfiles 
Scanning the distinfo file of every port in the tree ... done
purge_distfiles: Unknown error - directory search
Deleting distfiles/bash/bash43-014
Deleting distfiles/bash/bash43-015
Deleting distfiles/DBI-1.634.tar.gz
...

**Comment by jrmarino** [comment] 2016-03-06 00:24
Hi Bill, can you do this?

--- Makefile    (revision 410117)
+++ Makefile    (working copy)
@@ -19,7 +19,7 @@
 USE_GITHUB=    yes
 GH_ACCOUNT=    jrmarino
 GH_PROJECT=    synth_external:bundle
-GH_TAGNAME=    v1.3:bundle
+GH_TAGNAME=    v1.3:bundle fdd44ee


Then run "make makesum"
Then run "make deinstall; make clean ; make install"

Then try purging distfiles again.
It will stop when it its the error (I think) and it should give us more
information about what failed.

Thanks,
John

P.S. you may want to preinstall gcc6-aux if you don't already have it
installed.

**Comment by richterb1** [comment] 2016-03-06 01:05
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
purge_distfiles: Unknown error - directory search
raised CONSTRAINT_ERROR : PortScan.portkey_crate.Insert: attempt to
insert key already in map 

Distfile purge operation aborted.
# 

On 2016-03-05 04:24 PM, jrmarino wrote:

> Hi Bill, can you do this?
> 
> --- Makefile (revision 410117)
> +++ Makefile (working copy)
> @@ -19,7 +19,7 @@
> USE_GITHUB= yes
> GH_ACCOUNT= jrmarino
> GH_PROJECT= synth_external:bundle
> -GH_TAGNAME= v1.3:bundle
> +GH_TAGNAME= v1.3:bundle fdd44ee
> 
> Then run "make makesum"
> Then run "make deinstall; make clean ; make install"
> 
> Then try purging distfiles again.
> It will stop when it its the error (I think) and it should give us more
> information about what failed.
> 
> Thanks,
> John
> 
> P.S. you may want to preinstall gcc6-aux if you don't already have it
> installed.
> 
> On 3/6/2016 12:58 AM, richterb1 wrote:
>> Much seems to depend on what directory you start synth in.
>> 
>> 
>> synth purge-distfiles
>> 
>> Scanning the distinfo file of every port in the tree ... done
>> purge_distfiles: Unknown error - directory search
>> Deleting distfiles/bash/bash43-014
>> Deleting distfiles/bash/bash43-015
>> Deleting distfiles/DBI-1.634.tar.gz
>> ....
>> 
>> #cd /usr/ports
>> 
>> 
>> synth purge-distfiles
>> 
>> Scanning the distinfo file of every port in the tree ... done
>> purge_distfiles: Unknown error - directory search
>> Deleting distfiles/bash/bash43-014
>> Deleting distfiles/bash/bash43-015
>> Deleting distfiles/DBI-1.634.tar.gz
>> ...
>> 
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jrmarino/synth/issues/41>.
>> 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192766564

**Comment by jrmarino** [comment] 2016-03-06 01:30
Can you repeat but using the new hash of c56689a ?
I'm hopefully that will resolve the purge-distfiles command failure.

**Comment by jrmarino** [comment] 2016-03-06 01:31
wait hold on!

**Comment by jrmarino** [comment] 2016-03-06 01:37
It probably doesn't matter, but hash 332fc32 is more correct.  Can you try it?

**Comment by richterb1** [comment] 2016-03-06 01:44
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Searching /usr/ports/distfiles/xorg/lib directory is not supported
Searching /usr/ports/distfiles/xorg/data directory is not supported
... bunch of similar messages 
Searching /usr/ports/distfiles/repacked directory is not supported
Searching /usr/ports/distfiles/win32 directory is not supported
Searching /usr/ports/distfiles/texinfo/6.0.20151108 directory is not
supported
Distfile purge operation aborted.
# 

On 2016-03-05 05:37 PM, jrmarino wrote:

> It probably doesn't matter, but hash 332fc32 [1] is more correct. Can you try it? 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1]
https://github.com/jrmarino/synth/commit/332fc32544377395848a1173f731106b7179ffe0
[2] https://github.com/jrmarino/synth/issues/41#issuecomment-192777867

**Comment by jrmarino** [comment] 2016-03-06 01:49
that's surprising.
1) Do those directories exist?
2) If yes, is there anything strange about them?  Permissions?  Anything to prevent Synth from reading them?

**Comment by richterb1** [comment] 2016-03-06 01:57
# ls -l /usr/ports/distfiles/xorg/
total 32
drwxr-xr-x 2 root wheel 512 Mar 5 17:50 app
drwxr-xr-x 2 root wheel 512 Mar 5 15:12 data
drwxr-xr-x 2 root wheel 512 Mar 5 15:12 driver
drwxr-xr-x 2 root wheel 2048 Mar 5 15:12 font
drwxr-xr-x 2 root wheel 1024 Mar 5 17:55 lib
drwxr-xr-x 2 root wheel 512 Mar 5 17:48 proto
drwxr-xr-x 2 root wheel 512 Mar 5 17:52 util
drwxr-xr-x 2 root wheel 512 Mar 5 15:12 xserver
# 

No, don't see any reason why synth can't read them. 

# cd /usr/ports/distfiles/xorg/lib
# ls -l
total 18512
-rw-r--r-- 1 root wheel 384921 Jun 6 2014 libICE-1.0.9.tar.bz2
-rw-r--r-- 1 root wheel 348908 Sep 7 2013 libSM-1.2.2.tar.bz2
-rw-r--r-- 1 root wheel 2363858 Mar 9 2015 libX11-1.6.3.tar.bz2 

On 2016-03-05 05:50 PM, jrmarino wrote:

> that's surprising.
> 1) Do those directories exist?
> 2) If yes, is there anything strange about them? Permissions? Anything to prevent Synth from reading them? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192780024

**Comment by jrmarino** [comment] 2016-03-06 02:28
what cwd are you launching synth from?  specifically is it in /usr/ports somewhere?  if so, can you switch to say "/" or "/root" and try again?

**Comment by jrmarino** [comment] 2016-03-06 02:29
(I'll check answer in morning, it's super late here)

**Comment by richterb1** [comment] 2016-03-06 02:44
# pwd
/tmp
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Searching /usr/ports/distfiles/rpm/i686/centos/6.7 directory is not
supported
Searching /usr/ports/distfiles/rpm/i386/fedora/10 directory is not
supported
Searching /usr/ports/distfiles/KDE/4.14.3/kde-l10n directory is not
supported
Searching /usr/ports/distfiles/rpm/i686/centos directory is not
supported
Searching /usr/ports/distfiles/rpm/i386/fedora directory is not
supported 

On 2016-03-05 06:28 PM, jrmarino wrote:

> what cwd are you launching synth from? specifically is it in /usr/ports somewhere? if so, can you switch to say "/" or "/root" and try again? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192783406

**Comment by jrmarino** [comment] 2016-03-06 08:53
is that the complete output?  Meaning if you switch to /tmp and run purge-distfiles, those exact 5 lines (and no more) are outputted?

**Comment by jrmarino** [comment] 2016-03-06 09:57
If those are the exact lines (4 of which are linux RPM directories) then I'd start suspecting the contents of those directories has the explanation.  e.g. dangling symlinks?

**Comment by richterb1** [comment] 2016-03-06 15:48
I fetched all of the distfiles for my installed ports. 

No, that is not all the output and no synth doesn't say why it is
aborting. 

There was a previous message I thought that had the entire output. 

Note that I just rebuilt all 531 ports after thinking corruption in
/var/synth/live_packages/All.  

# more synth.ini
; This Synth configuration file is automatically generated
; Take care when hand editing! 

[Global Configuration]
profile_selected= LiveSystem 

[LiveSystem]
Operating_system= FreeBSD
Directory_packages= /var/synth/live_packages
Directory_repository= /var/synth/live_packages/All
Directory_portsdir= /usr/ports
Directory_options= /var/db/ports
Directory_distfiles= /usr/synth
Directory_buildbase= /usr/obj/synth-live
Directory_logs= /var/log/synth
Directory_ccache= disabled
Directory_system= /
Number_of_builders= 2
Max_jobs_per_builder= 4
Tmpfs_workdir= true
Tmpfs_localbase= true
Display_with_ncurses= true
leverage_prebuilt= false 

I don't recall creating this symlink, 

# pwd
/usr/ports
# cd distfiles
# ls -l distfiles
lrwxr-xr-x 1 root wheel 20 Feb 2 15:52 distfiles -> /usr/ports/distfiles
# 

# cd /usr/synth
# ls
Archive-Tar-2.04.tar.gz
Authen-SASL-2.16.tar.gz
Babel-2.2.0.tar.gz
CGI-4.27.tar.gz
CGI-Fast-2.10.tar.gz 

... 

387 files in this directory 

# pwd
/usr/synth
# cd /usr/synth/distfiles
cd: /usr/synth/distfiles: No such file or directory
# 

Here is the full output with all the port distfiles restored: 

# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting distfiles/bash/bash43-014 

raised ADA.IO_EXCEPTIONS.NAME_ERROR : file
"/usr/synth/distfiles/bash/bash43-014" does not exist
# 

On 2016-03-06 01:57 AM, jrmarino wrote:

> If those are the exact lines (4 of which are linux RPM directories) then I'd start suspecting the contents of those directories has the explanation. e.g. dangling symlinks? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192862141

**Comment by jrmarino** [comment] 2016-03-06 15:59
i'm a bit confused.
can you just do this?
1) move all the distfiles to "/distfiles" (or just pick a place that is not /usr/ports/..)
2) run "synth configure" and set the disfiles location to that location
3) add "DISTDIR=/distfiles" to your make.conf (or your picked location).  This is only so building directly from ports still works.

**Comment by jrmarino** [comment] 2016-03-06 16:01
to be clear, if /usr/ports/distfiles is the true place, "mv /usr/port/distfiles /distfiles"

/usr/port/distfiles is okay, but the configuration of /usr/synth with a symlink probably is the issue.  changing it to "/usr/ports/distfiles" will probably also fix the issue.

**Comment by richterb1** [comment] 2016-03-06 16:02
For clarity. 

# cd /tmp
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting distfiles/bash/bash43-014 

raised ADA.IO_EXCEPTIONS.NAME_ERROR : file
"/usr/synth/distfiles/bash/bash43-014" does not exist
# 

# pkg info bash*
bash-4.3.42_1
# 

# ls -l /usr/synth/bas*
total 16096
-rw-r--r-- 1 root wheel 7955839 Feb 26 2014 bash-4.3.tar.gz 

# ls -l /usr/ports/distfiles/bash*
total 16096
-rw-r--r-- 1 root wheel 7955839 Feb 26 2014 bash-4.3.tar.gz 

# ls /usr/synth/dis*
ls: /usr/synth/dis*: No such file or directory
# 

# cat synth.ini
; This Synth configuration file is automatically generated
; Take care when hand editing! 

[Global Configuration]
profile_selected= LiveSystem 

[LiveSystem]
Operating_system= FreeBSD
Directory_packages= /var/synth/live_packages
Directory_repository= /var/synth/live_packages/All
Directory_portsdir= /usr/ports
Directory_options= /var/db/ports
Directory_distfiles= /usr/synth
Directory_buildbase= /usr/obj/synth-live
Directory_logs= /var/log/synth
Directory_ccache= disabled
Directory_system= /
Number_of_builders= 2
Max_jobs_per_builder= 4
Tmpfs_workdir= true
Tmpfs_localbase= true
Display_with_ncurses= true
leverage_prebuilt= false

**Comment by jrmarino** [comment] 2016-03-06 16:04
what is unclear is why you have synth configured for distfiles at /usr/synth when this is clearly a lie.
Why not configure the distfiles directory to where it really is?

**Comment by richterb1** [comment] 2016-03-06 16:44
I don't recall doing that nor do I understand why there is the symlink. 
I re read the instructions.  When I installed this I recall using the
default setup. 

# cat synth.ini
; This Synth configuration file is automatically generated
; Take care when hand editing! 

[Global Configuration]
profile_selected= LiveSystem 

[LiveSystem]
Operating_system= FreeBSD
Directory_packages= /var/synth/live_packages
Directory_repository= /var/synth/live_packages/All
Directory_portsdir= /usr/ports
Directory_options= /var/db/ports
Directory_distfiles= /usr/ports/distfiles
Directory_buildbase= /usr/obj/synth-live
Directory_logs= /var/log/synth
Directory_ccache= disabled
Directory_system= /
Number_of_builders= 2
Max_jobs_per_builder= 4
Tmpfs_workdir= true
Tmpfs_localbase= true
Display_with_ncurses= true
leverage_prebuilt= false 

#pwd
/tmp
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting HTTP-Date-6.02.tar.gz
Deleting pciids-20160116.tar.xz
Deleting xorg/proto/xf86driproto-2.1.1.tar.bz2
Deleting xorg/lib/libxkbui-1.0.2.tar.bz2
Deleting xorg/font/font-screen-cyrillic-1.0.4.tar.bz2
Deleting v4l-utils-1.6.3.tar.bz2
Deleting xdg-utils-1.1.1.tar.gz
Deleting jrmarino-synth-v1.11-fdd44ee_GH0.tar.gz
Deleting shared-mime-info-1.5.tar.xz
Deleting linux-3.16.7-dvb-headers.tar.xz
Deleting curl-7.47.0.tar.lzma
Deleting pciids-20160227.tar.xz
Recovered 5.00 megabytes
# 

# pkg info pciids
pciids-20160227 

but it was removed but it's an installed port. 

Mar 6 08:32:52 <user.notice> binkley pkg: pciids upgraded: 20160116 ->
20160227 

here I did the make fetch to restore it. 

=> pciids-20160227.tar.xz doesn't seem to exist in
/usr/ports/distfiles/. 

# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting pciids-20160227.tar.xz
Recovered 177.00 kilobytes
# 

2016-03-06 08:05 AM, jrmarino wrote:

> what is unclear is why you have synth configured for distfiles at /usr/synth when this is clearly a lie.
> Why not configure the distfiles directory to where it really is? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192921231

**Comment by jrmarino** [comment] 2016-03-06 17:07
to summarize:
purge-distfiles is now working after fixing the configuration, except it thinks pciids-20160227.tar.xz is obsolete and deletes it repeatedly.

right?

**Comment by richterb1** [comment] 2016-03-06 18:36
I just ran a match fetch on all the 'installed ports'.  These are
deleted, but shouldn't be. 

# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting HTTP-Date-6.02.tar.gz
Deleting xorg/proto/xf86driproto-2.1.1.tar.bz2
Deleting xorg/lib/libxkbui-1.0.2.tar.bz2
Deleting xorg/font/font-screen-cyrillic-1.0.4.tar.bz2
Deleting v4l-utils-1.6.3.tar.bz2
Deleting xdg-utils-1.1.1.tar.gz
Deleting shared-mime-info-1.5.tar.xz
Deleting linux-3.16.7-dvb-headers.tar.xz
Deleting pciids-20160227.tar.xz
Recovered 2.00 megabytes
# 

# pkg info -E p5-HTTP-Date
p5-HTTP-Date-6.02_1 

On 2016-03-06 09:07 AM, jrmarino wrote:

> to summarize:
> purge-distfiles is now working after fixing the configuration, except it thinks pciids-20160227.tar.xz is obsolete and deletes it repeatedly. 
> 
> right? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192937129

**Comment by jrmarino** [comment] 2016-03-06 18:46
i could reproduce it, but I couldn't understand what was going on until very recently.  I'm on the trail to the fix.

**Comment by jrmarino** [comment] 2016-03-06 19:08
I had to back out all the RSA key work I done to add this fix, so hopefully I did that correctly.  Can you check hash 96c846b ?  I'm hopefully that solves purge-distfiles finally.

**Comment by richterb1** [comment] 2016-03-06 20:01
# cd /tmp
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Deleting jrmarino-synth-v1.11-332fc32_GH0.tar.gz
Recovered 91.00 kilobytes
# 

# cd /usr/ports/accessibility/dasher
# make fetch
===> dasher-4.10.1_8,2 depends on file: /usr/local/sbin/pkg - found
=> dasher-4.10.1.tar.bz2 doesn't seem to exist in
/usr/ports/distfiles/gnome2.
=> Attempting to fetch
https://download.gnome.org/sources/dasher/4.10/dasher-4.10.1.tar.bz2
dasher-4.10.1.tar.bz2 100% of 6522 kB 160 kBps 00m41s
===> Fetching all distfiles required by dasher-4.10.1_8,2 for building
# synth purge-distfiles
Scanning the distinfo file of every port in the tree ... done
Recovered 0.00 kilobytes
# 

# pkg info dasher*
pkg: No package(s) matching dasher*
# 

# ls /usr/ports/distfiles/gnome2/dasher*
/usr/ports/distfiles/gnome2/dasher-4.10.1.tar.bz2
# 

On 2016-03-06 11:08 AM, jrmarino wrote:

> I had to back out all the RSA key work I done to add this fix, so hopefully I did that correctly. Can you check hash 96c846b [1] ? I'm hopefully that solves purge-distfiles finally. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1]
https://github.com/jrmarino/synth/commit/96c846bee065cc98a5726fe09d4fc6b66700e93d
[2] https://github.com/jrmarino/synth/issues/41#issuecomment-192964407

**Comment by jrmarino** [comment] 2016-03-06 20:52
dasher actually is not a good test, unless you witnessed it get removed repeatedly. I think you are thinking that if the port is not installed, the distfile will be removed.  That's not what its doing.  If the distfile matches *any* port, installed or not, it will not be removed.

So ports from your earlier list of repeated removals, including pciids, are the ones that should be tested.  They shouldn't be removed anymore.

**Comment by richterb1** [comment] 2016-03-06 21:27
Yes, that is exactly what I was thinking.   I just fetched that file
expecting it to be removed since it wasn't an installed port.  I was
expecting it to clean out distfiles than belong to ports no longer
installed.  

What you appear to mean is, synth will purge OLD distfiles of any port,
regardless of it's installation status. 

So I install a port, decide I don't want it and deinstall it, by design
make deinstall won't remove the source package. Nor will synth since it
meets the criteria of matching to a valid port.  It will clean out
distfiles that are no longer a valid port, like net/isc-dhcp42-relay. 

Wouldn't that be a nice feature, remove-distfiles, remove any distfile
that is not an installed port? 

But yes, now it works as you described.  I would suggest another line or
two in the man page that clearly says, purge-distfile will not remove a
file if it's a valid port even if it is not installed.  But it will
remove a distfile if it is installed, but removed  (I.E. found in
MOVED). Then there is no confusion.  Unless it's just me that's
confused. 

This looks good to move to production. 

On 2016-03-06 12:52 PM, jrmarino wrote:

> dasher actually is not a good test, unless you witnessed it get removed repeatedly. I think you are thinking that if the port is not installed, the distfile will be removed. That's not what its doing. If the distfile matches _any_ port, installed or not, it will not be removed. 
> 
> So ports from your earlier list of repeated removals, including pciids, are the ones that should be tested. They shouldn't be removed anymore. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-192989064

**Comment by jrmarino** [comment] 2016-03-06 21:34
what you wouldn't want is to termporarily deinstall a port that's already been fetch and have it blown aware.  Or worse, prefetch something and run purge-distfiles before it's installed.  (remember ports can be happily in the repo without being installed).

But all the above assumes that the repo is only for the localhost.  You can't assume that.  Your repo could be serving 2, 5, 10, 100 servers.  In that case, what is installed on the builder server (localhost) has no relevance.  It would only make sense if you could poll every client of the repository.

Thus Synth is extremely conservative.  If a tarball serves any port in the tree, it's considered valid.  The cost is some cheap disk space, but even with this conservative approach, Synth regularly purges gigabytes of distfiles.

The only issue here is the definition of "obsolete".  I've defined obsolete as something the ports tree cannot use in any case.

**Comment by jrmarino** [comment] 2016-03-06 21:41
P.S.  poudriere, portmaster, and portupgrade all have similar features that probably work on the installed basis, so someone that strongly disagrees with me still has options (although I don't expect it to be such a big deal that anyone actually installs one of those other programs just to extra-purge distfiles)

**Comment by jrmarino** [comment] 2016-03-06 21:52
I just checked the man page:
```
   synth purge-distfiles
     This is a useful command that will first scan the entire ports tree to
     gather a full list of distfiles used by ports, and then it will scan the
     contents of the given distfiles directory. All source distribution files
     that cannot be matched to at least one port will be removed. This can
     result in gigabytes of recovered disk space if significant time has
     passed since the distfiles directory was last cleaned.
```
It doesn't imply that it's installed packages only, I don't believe.  It seems clear to me (that it applies to any port in the tree).  I could be too close to it, but then again maybe you made some assumptions on how it worked based on how similar programs have done it in the past?
I'm not sure what I was change in that entry.

**Comment by richterb1** [comment] 2016-03-06 22:28
You are correct, past behaviour of other tools.  Portmaster often failed
to remove the distfile when updating.   The same question when you make
deinstall or deinstall-all, it doesn't remove the distfile.  Perhaps
deinstall-clean, which would deinstall the port as it does now and
remove the distfile. But as you point out that would have adverse issues
if multiple machines share the /usr/ports/distfiles. 

So I see the risks, I do the same thing with one source machine and
multiple machines build ports from it. 

So I would have liked the option to remove all distfiles unless it's
installed, give me the option to confirm delete or force.  Having said
that, it might also be out of scope for synth. 

I think I have this correct on the last part, if a port is installed,
but it is removed like devel/pear-IO_Bit, this will leave you in a bad
spot.  The distfile will be removed, but the port is still installed so
you can't build the port unless you have a  backup of the distfile and
port directory.  But this encourages upgrading.   It's just that it will
happen and leave you in a potentially bad spot. 

So I'd clarify the man page.

synth purge-distfiles
     This is a useful command that will first scan the entire ports tree
to
     gather a full list of distfiles used by ports, and then it will
scan the
     contents of the given distfiles directory. All source distribution
files
     that cannot be matched to at least one port will be removed. This
can
     result in gigabytes of recovered disk space if significant time has
     passed since the distfiles directory was last cleaned.

     A port that has been installed and then removed will not have the
distfile deleted.  
     Previous version(s)s of an installed port that have been left in
place, will be removed. 
     When a port is removed (I.E. found in the MOVED file) it will be
removed even if the port 
     is still installed.

On 2016-03-06 01:52 PM, jrmarino wrote:

> I just checked the man page:
> 
> synth purge-distfiles
> This is a useful command that will first scan the entire ports tree to
> gather a full list of distfiles used by ports, and then it will scan the
> contents of the given distfiles directory. All source distribution files
> that cannot be matched to at least one port will be removed. This can
> result in gigabytes of recovered disk space if significant time has
> passed since the distfiles directory was last cleaned.
> 
> It doesn't imply that it's installed packages only, I don't believe. It seems clear to me (that it applies to any port in the tree). I could be too close to it, but then again maybe you made some assumptions on how it worked based on how similar programs have done it in the past?
> I'm not sure what I was change in that entry. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-193003457

**Comment by jrmarino** [comment] 2016-03-06 22:39
On 3/6/2016 11:28 PM, richterb1 wrote:
> 
> So I'd clarify the man page.
> 
> synth purge-distfiles
> This is a useful command that will first scan the entire ports tree
> to
> gather a full list of distfiles used by ports, and then it will
> scan the
> contents of the given distfiles directory. All source distribution
> files
> that cannot be matched to at least one port will be removed. This
> can
> result in gigabytes of recovered disk space if significant time has
> passed since the distfiles directory was last cleaned.
> 
> A port that has been installed and then removed will not have the
> distfile deleted.
> Previous version(s)s of an installed port that have been left in
> place, will be removed.
> When a port is removed (I.E. found in the MOVED file) it will be
> removed even if the port
> is still installed.
> 

Having packages installed where the port origin has been removed has a
high liklihood of causing problems later.

The package in question can only be removed, it cannot be updated or
rebuilt.  We are definitely not encouraging people to keep their own
ports outside of the tree.  (but if they do, the distfile wouldn't be
removed so there's no problem)

I don't even want to mention the word "installed" with purge-distfiles
command explanation.  The install state of the localhost is irrelevant,
but mentioning it might imply relevance.  I also don't want to mention
MOVED file because synth doesn't use it and mentioning it can cause
confusion.

**Comment by jrmarino** [comment] 2016-03-06 22:56
On 3/6/2016 11:28 PM, richterb1 wrote:
> You are correct, past behaviour of other tools. Portmaster often failed
> to remove the distfile when updating. The same question when you make
> deinstall or deinstall-all, it doesn't remove the distfile. Perhaps
> deinstall-clean, which would deinstall the port as it does now and
> remove the distfile. But as you point out that would have adverse issues
> if multiple machines share the /usr/ports/distfiles.

I just remembered this:
Remember that portmaster installs BUILD dependencies because of it's
design.  Synth does not.  For example, on portmaster systems, "gmake" is
installed because it's needed to build ports.  On Synth systems, it
probably isn't installed.

With installation being the driver of what distfiles to keep, ports like
gmake would get their distfiles purged (they aren't installed).  So
portmaster's approach doesn't apply even if you could say "just consider
the localhost".  And you say portmaster is even buggy so I'm thinking
people will appreciate something more robust anyway.

**Comment by richterb1** [comment] 2016-03-06 23:08
Agreed. 

I was just looking to add clarity that it doesn't cleanup distfiles that
belong to ports that are not installed.  It will remove distfiles that
are from previous installed versions.  I assume that it will also remove
distfiles for ports that are deleted (I.E. found in MOVED). 

But cleaning the distfile process might be outside the scope of synth.  
Users could use a script with the output of pkg info to know what ports
are installed and delete ones that don't match.  This as you pointed out
has the problem of deleting ports used by another machine.  

Which then says synth is not meant for a 100% clean distfiles directory.
  Some user work is needed. 

So, I think we're good with the version tested. 

On 2016-03-06 02:56 PM, jrmarino wrote:

> On 3/6/2016 11:28 PM, richterb1 wrote:
>> You are correct, past behaviour of other tools. Portmaster often failed
>> to remove the distfile when updating. The same question when you make
>> deinstall or deinstall-all, it doesn't remove the distfile. Perhaps
>> deinstall-clean, which would deinstall the port as it does now and
>> remove the distfile. But as you point out that would have adverse issues
>> if multiple machines share the /usr/ports/distfiles.
> 
> I just remembered this:
> Remember that portmaster installs BUILD dependencies because of it's
> design. Synth does not. For example, on portmaster systems, "gmake" is
> installed because it's needed to build ports. On Synth systems, it
> probably isn't installed.
> 
> With installation being the driver of what distfiles to keep, ports like
> gmake would get their distfiles purged (they aren't installed). So
> portmaster's approach doesn't apply even if you could say "just consider
> the localhost". And you say portmaster is even buggy so I'm thinking
> people will appreciate something more robust anyway. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-193011515

**Comment by jrmarino** [comment] 2016-03-06 23:22
On 3/7/2016 12:08 AM, richterb1 wrote:
> Which then says synth is not meant for a 100% clean distfiles directory.
> Some user work is needed.

If having a 100% clean distfiles directory is a requirement, then user
work is need.  I don't think anybody would have this requirement.  The
percentage of cruft will be small and it will eventually go away on its
own when the port version gets upgrades (purge-distfiles will purge the
obsolete file and nothing else will fetch the new version).

So I'm not expecting anyone to bother because there's not much payoff.
I'd put "dirty" percentage at 2% or less.

John

**Comment by richterb1** [comment] 2016-03-06 23:28
Agreed,  I'm in that small percentage who like neat and tidy. 

On 2016-03-06 03:22 PM, jrmarino wrote:

> On 3/7/2016 12:08 AM, richterb1 wrote:
>> Which then says synth is not meant for a 100% clean distfiles directory.
>> Some user work is needed.
> 
> If having a 100% clean distfiles directory is a requirement, then user
> work is need. I don't think anybody would have this requirement. The
> percentage of cruft will be small and it will eventually go away on its
> own when the port version gets upgrades (purge-distfiles will purge the
> obsolete file and nothing else will fetch the new version).
> 
> So I'm not expecting anyone to bother because there's not much payoff.
> I'd put "dirty" percentage at 2% or less.
> 
> John 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/41#issuecomment-193014915

**Comment by jrmarino** [comment] 2016-03-08 01:58
version 1.20 is available now, so closing this ticket.

**Closed by jrmarino** 2016-03-08 01:58 UTC
Labels: bug
