### ISSUE TITLE
net-im/ejabberd expects input during sanity check

### ISSUE THREAD

**Issue by GitHubinat0r** [jrmarino/synth#150] opened 2019-02-15 06:46 UTC
My Synth build machine skips over net-im/ejabberd due to it expecting input during sanity check. Is there some way to set auto-yes? I didn't see it referenced in the manual.

--------------------------------------------------------------------------------
--  Phase: check-sanity
--------------------------------------------------------------------------------
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: ###  Watchdog killed runaway process!  (no activity for 1 minutes)  ###

**Comment by jrmarino** [comment] 2019-02-15 06:59
you've got some major issue.
The "package management" tool is pkg(8).  That's supposed to be there.
Either you've got a messed up [profile]-make.conf or something else really not normal.
Or maybe some maintainer broke the port.

**Comment by GitHubinat0r** [comment] 2019-02-15 07:21
My [profile]-make.conf isn't that exciting (See below). It's only for this port (out of several hundred). I will tinker with the Makefile and see if I can figure out what the cause is. Aside from going down this route, is there anyway to automatically say yes to prompts using Synth?

```
CPUTYPE?=core2
MAKE_JOBS_NUMBER=4

OPTIONS_SET= UTF8 CPUFLAGS CPU_OPTS OPTIMIZED_CFLAGS BUILD_OPTIMIZED OPTIMIZED_FLAGS PGSQL SIP STUN SASL SASLMIT
OPTIONS_UNSET= CUPS X11 OPENGL EXAMPLES DOCS NLS DOXYGEN MANPAGES TEST MAN3 V4L OPENCV PULSEAUDIO JACK WAYLAND LIRC VDPAU QT5 QT4 MYSQL

.if ${.CURDIR:M*/ports/devel/ccache}                                    
  NO_CCACHE= yes
.endif
```

**Comment by jrmarino** [comment] 2019-02-15 13:11
What's going on with this make.conf?
The MAKE_JOBS_NUMBER line and the ccache stuff should *NOT* be there.
That looks like a straight copy-without-thinking job from some other file.

Here's a thought:
1) Create a new profile (means no make.conf used)
2) configure it
3) build net-im/ejabberd

if it works, it was your make.conf.

**Comment by GitHubinat0r** [comment] 2019-02-15 20:33
I found the offending line in the MakeFile. It now compiles without it. Is there anything I can do from the synth side for ports like this one?

pre-everything::
       @if pkg query %n-%v net-im/ejabberd; then \
               ${ECHO_MSG} needs to be uninstalled, before this port build could proceed. ; \
               ${ECHO_MSG} For details: https://github.com/processone/ejabberd/issues/2194 ; \
               ${ECHO_MSG} Sorry for the inconvenience. ; \
               exit 1; \
       fi

**Comment by jrmarino** [comment] 2019-02-15 20:41
OMG.
That is moronic.
You should tell the maintainer (via email or PR) that if they are going to abuse the ports system and write makefiles that favor live-system building over poudriere/synth (a horrible idea) then at least he should wrap that inside a ".if !defined(PACKAGE_BUILDING)" clause.

This is a bad mistake by the maintainer (indicates lack of awareness or respect for the package builders) and it should be fixed there.

**Comment by jrmarino** [comment] 2019-02-15 20:42
for fun, you should remove the leading "@" to see what error synth is actually hitting.  The pkg package isn't installed yet maybe?

**Comment by GitHubinat0r** [comment] 2019-02-16 06:50
See below. 

I'll ping the package manager with your recommendation. 

Thanks for your in-depth and prompt recommendations.


```
 --------------------------------------------------------------------------------
 --  Phase: check-sanity
 --------------------------------------------------------------------------------
 if pkg query %n-%v net-im/ejabberd; then  echo needs to be uninstalled, before this port build could proceed. ;  echo For details: https://github.com/processone/ejabber
 The package management tool is not yet installed on your system.
 Do you want to fetch and install it now? [y/N]: ###  Watchdog killed runaway process!  (no activity for 1 minutes)  ###
```

**Closed** 2019-02-16 08:10 UTC

**Comment by jrmarino** [comment] 2019-02-17 22:02
okay, so that's an OS script that runs when pkg isn't found I think.
The problem is that the sanity-check target never should have been written (as we already discussed).

**Comment by GitHubinat0r** [comment] 2019-02-17 22:08
Understood. 

The port maintainer is about to rollout a fix. 

Thanks again!

**Comment by jrmarino** [comment] 2019-02-20 14:29
I see the fix.  It's still bad.  If the maintainer is insisting to value "live system" building over builders like poudriere or synth, he should be checking if PACKAGE_BUILDING is set (the builders set this variable in the environment, so if the variable is set, there's no point in doing the sanity check because the port knows the environment is clean)
