### ISSUE TITLE
Confusing error when /usr/ports/distfiles doesn't exist

### ISSUE THREAD

**Issue by assistcontrol** [jrmarino/synth#11] opened 2016-01-28 02:38 UTC
On a completely cherry system, /usr/ports/distfiles doesn't exist yet. This leads to the following exchange:

```
root@testbox:~ # pkg install synth
Installing pkg-1.6.2...
Extracting pkg-1.6.2: 100%
[1/2] Installing ncurses-6.0_2...
[1/2] Extracting ncurses-6.0_2: 100%
[2/2] Installing synth-0.99...
[2/2] Extracting synth-0.99: 100%
root@testbox:~ # synth configure
At least one directory in the configuration is invalid
root@testbox:~ # synth install [anything]
At least one directory in the configuration is invalid
```

The error message is accurate, but still confusing. One of the following would make the new-user process much easier, as it will be encountered on _all_ new boxes:

1. Create /usr/ports/distfiles if it doesn't exist---it's the only thing that needs to be done before synth runs happily

2. Instead of "At least one directory[...] is invalid", say "Directory /path/to/foo, specified in configuration, doesn't exist

**Comment by jrmarino** [comment] 2016-01-28 07:03
There's a problem with #1: It's an absurd default.  We shouldn't be enforcing it.  With how it is now, the user has a chance to change it to something better, but if the default is just automatically created then the user won't get the chance.

maybe we can print out the directories that are missing though, and even specifically suggest changing distfiles configuration if that's the one that missing (against to a better directory that's not located in the ports tree)

**Comment by jrmarino** [comment] 2016-01-28 07:04
to be clear, synth is getting the distfiles value from the ports tree rather than making on up, but since the tree is pristine, it's return the default value.

**Comment by jrmarino** [comment] 2016-01-28 09:00
Okay, I think I have this addressed and it will be fixed in the next issue.

I found out that you can't run "synth configure" in this case either, which is really bad, so that's been fixed too.

**Comment by assistcontrol** [comment] 2016-02-04 18:34
This made it into synth-0.99_2, yes?

On a fresh system I'm still getting:

```
root@testbox2:~ # ls /usr/ports/distfiles
ls: /usr/ports/distfiles: No such file or directory
root@testbox2:~ # synth configure
Configuration failed to load.
```

The error message doesn't seem to be getting displayed?

**Comment by jrmarino** [comment] 2016-02-04 18:44
i don't know.  Can you retry with 0.99_5 ?

**Comment by jrmarino** [comment] 2016-02-04 18:46
works for me:
```
ironwolf# /home/marino/synth/build/synth just-build games/2048 games/alienwave games/aop games/avanor
Configuration invalid: [C] Distfiles directory: /usr/dports/distfiles
```

**Comment by jrmarino** [comment] 2016-02-04 18:46
there's significant fixes between _2 and _5, so the very latest should be tested.

**Comment by assistcontrol** [comment] 2016-02-04 18:51
Sorry I should have specified there. Completely cherry box, `pkg install synth` which installed 0.99_4.

**Comment by jrmarino** [comment] 2016-02-04 18:53
hmmm, yes it should be fixed by 99_4.

**Comment by jrmarino** [comment] 2016-02-04 18:55
can you paste /usr/local/etc/synth/synth.ini  here?

**Comment by jrmarino** [comment] 2016-02-07 20:48
i tried to reproduce this on FreeBSD 11/1386 and I cannot
I deleted /usr/port/distfiles and /usr/local/etc/synth completely and 0.99_4 always provides the correct error message.

**Comment by assistcontrol** [comment] 2016-02-10 00:10
Sorry about the delay, John. I tried to recreate the VM that I ran into that problem with but I can't reproduce it. Either I did something really dumb to get that error in the first place, or you've since fixed whatever message I ran into. Either way, sorry about the noise and thanks for your patience.

**Closed** 2016-02-10 09:23 UTC
