### ISSUE TITLE
raised PORTSCAN.SEEK_FAILURE

### ISSUE THREAD

**Issue by richterb1** [jrmarino/synth#40] opened 2016-03-05 19:51 UTC
Since the recent change to speed up the respository build, I now get this message.

raised PORTSCAN.SEEK_FAILURE : www/apache22 was expected to be blocked by textproc/expat2

I don't understand the message so I'm puzzled how to fix it.  It would be good if the man page had a listing of various errors and sample solutions.  The source code doesn't help explain what will cause this error. 

I've updated Makefile.local for apache22 and mod_evasive by adding 
IGNORE= using apache24

# synth upgrade-system
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
After inspection, it has been determined that there are no packages that
require rebuilding; the task is therefore complete.
Stand by, prescanning existing packages.
Stand by, recursively scanning 532 ports serially.
Scanning existing packages.
 progress: 97.06%              

raised PORTSCAN.SEEK_FAILURE : www/apache22 was expected to be blocked by textproc/expat2

-=>  Chronology of last build  <=-
Started: Saturday, 5 MAR 2016 at 19:37:05 UTC
Ports to build: 532

Purging any ignored/broken ports first ...
00:00:10 www/apache22 has been ignored: Using apache24
           Skipped: www/mod_evasive
00:00:10 Sanity check complete. Ports remaining to build: 0
Finished: Saturday, 5 MAR 2016 at 19:37:16 UTC
Duration: 00:00:10

I wouldn't expect to see the error since apache22 shouldn't be built and expat2 isn't dependant on apache.  But I don't understand the portscan failure message, which appears to not be in man page nor logs.  

# synth install textproc/expat2
After inspection, it has been determined that there are no packages that
require rebuilding; the task is therefore complete.
Stand by, prescanning existing packages.
Stand by, recursively scanning 531 ports serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100%    260 B   0.3kB/s    00:01    
Fetching packagesite.txz: 100%  128 KiB 131.4kB/s    00:01    
Processing entries: 100%
Synth repository update completed. 531 packages processed.
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
The following 5 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	xmlto: 0.0.28 [Synth]
	xorg-server: 1.17.4,1 [Synth]
	ninja: 1.6.0,2 [Synth]
	p5-Try-Tiny: 0.24 [Synth]

Installed packages to be UPGRADED:
	graphite2: 1.3.5 -> 1.3.6 [Synth]

The process will require 5 MiB more space.
[1/5] Upgrading graphite2 from 1.3.5 to 1.3.6...
[1/5] Extracting graphite2-1.3.6: 100%
[2/5] Installing xmlto-0.0.28...
[2/5] Extracting xmlto-0.0.28: 100%
[3/5] Installing xorg-server-1.17.4,1...
[3/5] Extracting xorg-server-1.17.4,1: 100%
[4/5] Installing ninja-1.6.0,2...
[4/5] Extracting ninja-1.6.0,2: 100%
[5/5] Installing p5-Try-Tiny-0.24...
[5/5] Extracting p5-Try-Tiny-0.24: 100%
Message from xmlto-0.0.28:
For benefits of conversions away from XHTML1 through XSL-FO,
a stylesheet xhtml2fo.xsl has been installed
into /usr/local/share/xmlto. Example use:

  xmlto pdf -x /usr/local/share/xmlto/xhtml2fo.xsl myXHTML1file.xml

More style sheets for XHTML1 conversions can be found at
<http://www.antennahouse.com/XSLsample/XSLsample.htm>
under "Stylesheet for XHTML to XSL-FO transformation"

ran make update 
...
Updated to revision 410204.

# synth upgrade-system
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
 progress: 94.59%              

The task is complete.  Final tally:
Initial queue size: 3
    packages built: 1
           ignored: 1
           skipped: 1
            failed: 0

Duration: 00:00:18
The build logs can be found at: /var/log/synth
Stand by, prescanning existing packages.
Removed: intltool-0.51.0.txz   
Stand by, recursively scanning 532 ports serially.
Scanning existing packages.
 progress: 91.00%              

raised PORTSCAN.SEEK_FAILURE : www/apache22 was expected to be blocked by textproc/expat2

**Comment by jrmarino** [comment] 2016-03-05 20:10
it's an integrity check failure.  no "raised" messages should be documented because either it's fatal or it should be handled (in other words, it's a bug that the error isn't handled).

Back to issue:
is apache22 on your system?
Do you see an apache22 package in the local packages directory?

**Comment by jrmarino** [comment] 2016-03-05 20:11
ah, "00:00:10 www/apache22 has been ignored: Using apache24"

That's probably significant

**Comment by jrmarino** [comment] 2016-03-05 20:32
I'm pretty sure www/mod_evasive is the problem.
That's an apache22 module, but you're using Apache24. You need to remove that package (it might be in the repository but not installed).

I'll have to try to reproduce this locally to see how Synth can be handle this using the new "fast" repo validating scheme.

**Comment by richterb1** [comment] 2016-03-05 22:30
I have set mod_evasive to ignore because they don't have the port built
correctly to understand the changes needed for apache24.  So I fix
mod_evasive manually and install the port but tell the tools to avoid
it. 

I did find /usr/ports/distfiles/apache22  and just removed it, but there
is no package installed.  In a fit, I erased the synth packages and
rebuilt them all from scratch. 

 # pkg info apache*
apache24-2.4.18 

I can't seem to figure out what port has the dependency on apache22,
mod_evasive does, but the tools have  been told to ignore it.   So what
it appears is synth is trying to build apache22 as a dependency for
mod_evasive.  But both ports are set to ignore. So it shouldn't matter
about the apache dependency in mod_evasive. 

I wish they would create mod_evasive22 and mod_evasive24.   Better is
just adding the few fixes in the port to build it correctly depending on
apache22 or apache24. 

So, in summary. 

0. USE_APACHE= 24 in mod_evasive is a temporary fix. 

1. It would be good to add some more 'documentation' on those FATAL
errors.  In this case more help to understand what blocking means and
why it's fatal.  I.E. if interactive, give the option to skip the port
and continue.  In this case, I'm guessing it's detected apache24 is
installed and you can't install apache22 cause it puts files in the same
place.  

2. www/mod_evasive is the problem,  synth is doing a good job, it uses
USE_APACHE= 24 in mod_evasive to try to build apache22,  But then finds
the block issue. 

3. I would expect when it tries to build apache22 it would see the
IGNORE and skip it. In theory, it should find the IGNORE in mod_evasive
first and not even try to build apache22 OR mod_evasive. 

Updated to revision 410214.
# synth upgrade-system
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
After inspection, it has been determined that there are no packages that
require rebuilding; the task is therefore complete.
Stand by, prescanning existing packages.
Stand by, recursively scanning 532 ports serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100% 260 B 0.3kB/s 00:01 
Fetching packagesite.txz: 100% 128 KiB 131.5kB/s 00:01 
Processing entries: 100%
Synth repository update completed. 531 packages processed.
Checking for upgrades (171 candidates): 100%
Processing candidates (171 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date 

On 2016-03-05 12:32 PM, jrmarino wrote:

> I'm pretty sure www/mod_evasive is the problem.
> That's an apache22 module, but you're using Apache24. You need to remove that package (it might be in the repository but not installed). 
> 
> I'll have to try to reproduce this locally to see how Synth can be handle this using the new "fast" repo validating scheme. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192729630

**Comment by richterb1** [comment] 2016-03-05 22:36
On 2016-03-05 12:32 PM, jrmarino wrote:

> I'm pretty sure www/mod_evasive is the problem.
> That's an apache22 module, but you're using Apache24. You need to remove that package (it might be in the repository but not installed). 
> 
> I'll have to try to reproduce this locally to see how Synth can be handle this using the new "fast" repo validating scheme. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192729630

**Comment by jrmarino** [comment] 2016-03-05 22:42
deleting apache from distfiles doesn't do anything.  that's the source tarball.  I had meant to delete the package that I assumed had been built (it sounds like it hasn't been).

I have to try to understand how you hacked mod_evasive, but given how synth is acting, it's possible that the hack is bad.  (there's probably a reason evasive is marked apache22 only)

**Comment by richterb1** [comment] 2016-03-05 22:44
Just a followup. 

1. The error message was cryptic. 

2. I expected synth to skip both packages. 

3. I suspect it did, but in the repository checking it found the
installed package mod_evasive and the dependency for apache22. 

4. raised PORTSCAN.SEEK_FAILURE : www/apache22 was expected to be
blocked by textproc/expat2 seems completely unrelated. 

5. The error message might be:  raised PORTSCAN.SEEK_FAILURE :
www/apache22 is a dependency of www/mod_evasive but you have
www/apache24 installed. 

6. This case is unique because of the problem with mod_evasive port not
having a few lines in it to build correctly for apache22 or apache24. 
And caused by my need to have mod_evasive installed AND the changes
needed to build it for apache24 and those changes being overwritten by
SVN when the /usr/ports is updated. 

On 2016-03-05 12:32 PM, jrmarino wrote:

> I'm pretty sure www/mod_evasive is the problem.
> That's an apache22 module, but you're using Apache24. You need to remove that package (it might be in the repository but not installed). 
> 
> I'll have to try to reproduce this locally to see how Synth can be handle this using the new "fast" repo validating scheme. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192729630

**Comment by jrmarino** [comment] 2016-03-05 22:46
the error is FATAL so there's no getting past it.  In fact, I've never seen it even hit before.  It's doing the right thing though, it's a ports tree integrity failure.  The error is definitely not user-level, users will never see it on normal circumstances.

**Comment by jrmarino** [comment] 2016-03-05 22:47
> 4. raised PORTSCAN.SEEK_FAILURE : www/apache22 was expected to be
blocked by textproc/expat2 seems completely unrelated.

it's not unrelated at all.  expat2 is a dependency of apache22.

**Comment by jrmarino** [comment] 2016-03-05 22:51
as long as you have www_evasive installed and your ports tree is corrupt, the "upgrade-system" command isn't going to work.

I expect "synth rebuild-repository" command will work.
If /usr/local/etc/pkg/repos/00_synth.conf exists, you could upgrade your system manually with pkg(8), e.g. pkg upgrade -r Synth

**Comment by richterb1** [comment] 2016-03-05 22:55
Agreed, what I did find was synth purge-distfiles seems to delete
everything.  

Yes, there are just a few changes needed in the source and the library
name change for apache24.  Minor. 

In hindsight the better fix would be for me to make mod_evasive24 and
install it locally, but that was a lot more trouble.  I also thought
telling synth to IGNORE both packages would solve the problem.  But I'm
guessing again, it's not IGNORING in the repository search.  So the case
is unique to how I installed mod_evasive, but the work around to keep it
from being a problem generate the error.  The error message though
doesn't point to the problem that caused it, which is mod_evasive not
textproc/expat2 

So what I should/could have done was built my own mod_evasive24.tgx and
put that in the local repository. 

On 2016-03-05 02:42 PM, jrmarino wrote:

> deleting apache from distfiles doesn't do anything. that's the source tarball. I had meant to delete the package that I assumed had been built (it sounds like it hasn't been). 
> 
> I have to try to understand how you hacked mod_evasive, but given how synth is acting, it's possible that the hack is bad. (there's probably a reason evasive is marked apache22 only) 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192754288

**Comment by jrmarino** [comment] 2016-03-05 22:55
FYI, according to commit log, evasive doesn't work with apache24:

> Port build fails on local exp-run with apache24 with
 error: 'conn_rec' has no member named 'remote_ip'

is that obsolete?  Or have you fixed it?  the solution to your problem is to get the port fixed (or deinstall www_evasive)

**Comment by jrmarino** [comment] 2016-03-05 22:58
purge-distfiles was supposed to only remove distfiles that aren't anywhere in ports.  I just used it today and it was working fine.  It's actually pretty simple so I don't think there's a bug there.  Are saying it literally removed *every* file from the directory?

secondly, it's trying to build www_evasive because pkg(8) told synth that it's installed.  That's why it's on the build list.  (you might fool synth by moving /usr/ports/www/mod_evasive to /usr/ports/www/mod_evasive.skip.  That might cause Synth to ignore it and live it off the build list.  No promises but it's worth a shot.

**Comment by richterb1** [comment] 2016-03-05 23:00
I did run rebuild-repository too, I recall the same issue trying to
update. 

What I struggle with is why synth was trying to touch apache22 or
mod_evasive since both are set to IGNORE because I don't want apache22
built and I know I've 'corrupted' mod_evasive so don't build that
either. 

My thought is in this case synth should have skipped apache22 and any
dependency like expat2. 

But I would think the error message would be 'can't install apache22
since apache24 is already installed in the same place'.  But again, I've
told the the 'tools' IGNORE apache22 and mod_evasive.  But it seems
IGNORE doesn't work as I expect IF the package has already been
installed. 

On 2016-03-05 02:51 PM, jrmarino wrote:

> as long as you have www_evasive installed and your ports tree is corrupt, the "upgrade-system" command isn't going to work. 
> 
> I expect "synth rebuild-repository" command will work.
> If /usr/local/etc/pkg/repos/00_synth.conf exists, you could upgrade your system manually with pkg(8), e.g. pkg upgrade -r Synth 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192754782

**Comment by jrmarino** [comment] 2016-03-05 23:03
the IGNORE isn't the problem.
The problem is that your modifications are bad.  You broke the tree (I suspect it would break the INDEX).  This doesn't happen with stock trees -- Synth is strict and just ejects when it finds corruption.

At least that what I think is going on.

**Comment by jrmarino** [comment] 2016-03-05 23:06
to be clear, it's honoring the IGNORE.  It's failing during the impact cascade.  When it finishes a port (success, fail, skip, ignore) it adjusts all the ports that depend on it so the builders know when it a port is clear to build.  The cascade is falling due to dependency corruption.

**Comment by jrmarino** [comment] 2016-03-05 23:09
did you see this?
https://github.com/shivaas/mod_evasive

**Comment by richterb1** [comment] 2016-03-05 23:11
All that's needed is code in the Makefile to do patch if apache24... 

cp mod_evasive20.c mod_evasive24.c 
sed s/remote_ip/client_ip/g -i mod_evasive24.c 

USE_APACHE= 24 
MODULENAME= ${PORTNAME}24 

post-patch:
@${REINPLACE_CMD} -e "s|/bin/mail|/usr/bin/mail|g" \
${WRKSRC}/mod_evasive.c ${WRKSRC}/mod_evasive24.c \
${WRKSRC}/mod_evasiveNSAPI.c

You are correct, I've caused the issue by doing what I did. 

I should have built the package and installed it as mod_evasive24.tgx. 

My only issue with synth is I exected it to IGNORE any activity for
apache22 or mod_evasive. 

And the error message was/is confusing based on what the problem was
actually.  synth doesn't say why it is going to block. 

But based on your feedback I can clear the error.  Feel free to close
the ticket. 

On 2016-03-05 02:55 PM, jrmarino wrote:

> FYI, according to commit log, evasive doesn't work with apache24:
> 
>> Port build fails on local exp-run with apache24 with
>> error: 'conn_rec' has no member named 'remote_ip'
> 
> is that obsolete? Or have you fixed it? the solution to your problem is to get the port fixed (or deinstall www_evasive) 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192755425

**Comment by jrmarino** [comment] 2016-03-05 23:12
this is pertinent too, you might have done this:
https://project.altservice.com/issues/562

**Comment by richterb1** [comment] 2016-03-05 23:13
Correct.  

My assumption that IGNORE was global was faulty. 

But the error didn't point to the corrupted port, mod_evasive nor did it
say I can't install apache22 since apache24 is installed, a lesser
problem. 

On 2016-03-05 03:06 PM, jrmarino wrote:

> to be clear, it's honoring the IGNORE. It's failing during the impact cascade. When it finishes a port (success, fail, skip, ignore) it adjusts all the ports that depend on it so the builders know when it a port is clear to build. The cascade is falling due to dependency corruption. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192756732

**Comment by jrmarino** [comment] 2016-03-05 23:14
> synth doesn't say why it is going to block.

As I said, I never expected that error to get hit.  It's essentially an assertion.  There's no user action to take.

We should get that port fixed though, that's the real issue.  It seems that it's long overdue for apache24 support.

**Comment by richterb1** [comment] 2016-03-05 23:15
Yes, that's where I got the fix.  Sadly the freebsd port hasn't been
updated. 

On 2016-03-05 03:09 PM, jrmarino wrote:

> did you see this?
> https://github.com/shivaas/mod_evasive 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192756844

**Comment by jrmarino** [comment] 2016-03-05 23:16
I'm going to fix the port myself.  This is absurd.

**Comment by richterb1** [comment] 2016-03-05 23:19
That is what I basically did. 

But SVN restored the orginal file, which got me to the breakage and the
problem that the error message said it was apache22 which was set to
IGNORE.  But synth doesn't IGNORE during that repository check. 

On 2016-03-05 03:12 PM, jrmarino wrote:

> this is pertinent too, you might have done this:
> https://project.altservice.com/issues/562 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192757070

**Comment by richterb1** [comment] 2016-03-05 23:24
Yes.  That's the best fix. 

On 2016-03-05 03:14 PM, jrmarino wrote:

>> synth doesn't say why it is going to block.
> 
> As I said, I never expected that error to get hit. It's essentially an assertion. There's no user action to take. 
> 
> We should get that port fixed though, that's the real issue. It seems that it's long overdue for apache24 support. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192757212

**Comment by richterb1** [comment] 2016-03-05 23:25
You are my hero. 

On 2016-03-05 03:16 PM, jrmarino wrote:

> I'm going to fix the port myself. This is absurd. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192757773

**Comment by jrmarino** [comment] 2016-03-05 23:30
the altservice.com link says it's okay to keep using mod_evasive20.c (rather than mod_evasive24.c).

Do I need to do anything other than add the single sed command if APACHE_VERSION=24 ?

**Comment by jrmarino** [comment] 2016-03-05 23:33
I'm building www_evasive now, it pulled in apache24.  If all looks good, I'll post a patch.  If that patch solves your problem, I'll commit it.

**Comment by jrmarino** [comment] 2016-03-05 23:38
This works for me, can you patch a vanilla www_evasive and tell me if that solves the issue?

```
--- www/mod_evasive/Makefile    (revision 410117)
+++ www/mod_evasive/Makefile    (working copy)
@@ -16,7 +16,7 @@

 WRKSRC=                ${WRKDIR}/${PORTNAME}

-USE_APACHE=    22
+USE_APACHE=    22+
 AP_FAST_BUILD= yes
 AP_GENPLIST=   yes
 MODULENAME=    ${PORTNAME}20
@@ -23,13 +23,18 @@

 PORTDOCS=      README test.pl

+.include <bsd.port.pre.mk>
+
 post-patch:
        @${REINPLACE_CMD} -e "s|/bin/mail|/usr/bin/mail|g" \
                ${WRKSRC}/mod_evasive.c ${WRKSRC}/mod_evasive20.c \
                ${WRKSRC}/mod_evasiveNSAPI.c
+.if ${APACHE_VERSION:M24}
+       ${REINPLACE_CMD} -e 's/remote_ip/client_ip/g' ${WRKSRC}/mod_evasive20.c
+.endif

 post-install:
        @${MKDIR} ${STAGEDIR}${DOCSDIR}
        @${INSTALL_DATA} ${PORTDOCS:S|^|${WRKSRC}/|} ${STAGEDIR}${DOCSDIR}

-.include <bsd.port.mk>
+.include <bsd.port.post.mk>
```

**Comment by richterb1** [comment] 2016-03-05 23:39
I changed s/20/24/ for uniformity sake, just in case someone was using a
jail, you could then run apache22 and apache24 without conflict. 

So much depends on how you adjust the Makefile to create the new library
and the fix:

sed -i '' -e 's/remote_ip/client_ip/g' work/mod_evasive/mod_evasive20.c

But yes, the key is replacing remote_ip/client_ip. 

On 2016-03-05 03:30 PM, jrmarino wrote:

> the altservice.com link says it's okay to keep using mod_evasive20.c (rather than mod_evasive24.c). 
> 
> Do I need to do anything other than add the single sed command if APACHE_VERSION=24 ? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192758908

**Comment by richterb1** [comment] 2016-03-05 23:43
Well, yes, it will make mod_evasive work for apache22 or apache24
buiding with the right label. 

I already know USE_APACHE= 24 makes synth work correctly with my local
mod_evasive changes. 

On 2016-03-05 03:33 PM, jrmarino wrote:

> I'm building www_evasive now, it pulled in apache24. If all looks good, I'll post a patch. If that patch solves your problem, I'll commit it. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192759851

**Comment by jrmarino** [comment] 2016-03-05 23:45
I'm not following.
I'm assuming that if I commit that patch, you'd remove your local changes and synth would function as intended.  That solves the problem, right?

**Comment by jrmarino** [comment] 2016-03-05 23:56
I was able to build a repository, so I think my patch is correct.

**Comment by jrmarino** [comment] 2016-03-05 23:57
http://www.freshports.org/commit.php?category=www&port=mod_evasive&files=yes&message_id=201603052357.u25Nv0Gj017909@repo.freebsd.org

**Comment by richterb1** [comment] 2016-03-06 00:06
I just applied your patch.  

Only thing I recall was the port automatically added the LoadModule in
httpd.conf. 

But the code compiles and I added the LoadModule line manually and I'm
up and running and synth is happy too. 

# svn status
M Makefile
? work
# synth upgrade-system
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
progress: 92.13% 

The task is complete. Final tally:
Initial queue size: 1
packages built: 1
ignored: 0
skipped: 0
failed: 0 

Duration: 00:00:19
The build logs can be found at: /var/log/synth
Stand by, prescanning existing packages.
Stand by, recursively scanning 532 ports serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100% 260 B 0.3kB/s 00:01 
Fetching packagesite.txz: 100% 129 KiB 132.2kB/s 00:01 
Processing entries: 100%
Synth repository update completed. 532 packages processed.
Updating database digests format: 100%
Checking for upgrades (172 candidates): 100%
Processing candidates (172 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
# 

On 2016-03-05 03:45 PM, jrmarino wrote:

> I'm not following.
> I'm assuming that if I commit that patch, you'd remove your local changes and synth would function as intended. That solves the problem, right? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192761774

**Comment by jrmarino** [comment] 2016-03-06 00:08
so is the www/mod_evasive okay as is, or does it need to handle this loadmodule thing?

**Comment by richterb1** [comment] 2016-03-06 00:12
# make update
--------------------------------------------------------------
>>> Updating /usr/ports using Subversion
--------------------------------------------------------------
cd /usr/ports; /usr/bin/svnlite update
Updating '.':
Restored 'www/mod_evasive'
Restored 'www/mod_evasive/Makefile'
Restored 'www/mod_evasive/distinfo'
Restored 'www/mod_evasive/pkg-descr'
At revision 410219. 

# synth upgrade-system
Querying system about current package installations.
Stand by, comparing installed packages against the ports tree.
Scanning existing packages.
After inspection, it has been determined that there are no packages that
require rebuilding; the task is therefore complete.
Stand by, prescanning existing packages.
Stand by, recursively scanning 532 ports serially.
Scanning existing packages.
Packages validated, rebuilding local repository.
Local repository successfully rebuilt
Updating Synth repository catalogue...
Fetching meta.txz: 100% 260 B 0.3kB/s 00:01 
Fetching packagesite.txz: 100% 129 KiB 132.3kB/s 00:01 
Processing entries: 100%
Synth repository update completed. 532 packages processed.
Checking for upgrades (172 candidates): 100%
Processing candidates (172 candidates): 100%
Checking integrity... done (0 conflicting)
Your packages are up to date.
# 

#grep evasive httpd.conf
LoadModule evasive20_module libexec/apache24/mod_evasive20.so
<IfModule evasive20_module>
DOSLogDir "/var/log/mod_evasive.log"
# 
# /usr/local/sbin/apachectl start
Performing sanity check on apache24 configuration:
Syntax OK
Starting apache24.
# 

[Sat Mar 05 16:10:55.099358 2016] [mpm_prefork:notice] [pid 87382]
AH00163: Apac
he/2.4.18 (FreeBSD) OpenSSL/1.0.1p-freebsd configured -- resuming normal
operations
[Sat Mar 05 16:10:55.099550 2016] [core:notice] [pid 87382] AH00094:
Command lin
e: '/usr/local/sbin/httpd -D NOHTTPACCEPT'

Everything works as expected. 

On 2016-03-05 03:57 PM, jrmarino wrote:

> http://www.freshports.org/commit.php?category=www&port=mod_evasive&files=yes&message_id=201603052357.u25Nv0Gj017909@repo.freebsd.org 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192762316

**Comment by richterb1** [comment] 2016-03-06 00:17
I would say your changes would not have changed previous behaviour. 

I would say the normal behaviour is to manually update httpd.conf with
loadmodules you want configured. 

But my thought is, the port maintainer might have an option to "update
httpd.conf". 

I say it's good as it is. 

On 2016-03-05 

04:08 PM, jrmarino wrote:

> so is the www/mod_evasive okay as is, or does it need to handle this loadmodule thing? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/jrmarino/synth/issues/40#issuecomment-192764147

**Comment by jrmarino** [comment] 2016-03-06 00:26
good enough for me, let's close this.  I think Synth reacted as (I) expected.  This is one of many times that Synth has discovered an error in ports due to its strict integrity checks.  I think that's a good thing.

**Closed by jrmarino** 2016-03-06 00:26 UTC
Labels: bug
