### ISSUE TITLE
Synth threads exit with resources held

### ISSUE THREAD

**Issue by mjoras** [jrmarino/synth#97] opened 2017-09-21 03:43 UTC
Hello, I see this behavior regularly when using Synth. It happens more frequently the more parallel ports I build at once:

```
 Fatal error 'thread 0x80121ab00 exits with resources held!' at line 316 in file /usr/src/lib/libthr/thread/thr_exit.c (errno = 2)
```

This is on FreeBSD-CURRENT. From my reading of libthr this seems to indicate that a thread exited either with a lock held or while in some sort of critical section. Is there anything I can do to help debug the problem further? It is fairly reproducible whenever I build a large number of ports.

**Comment by jrmarino** [comment] 2017-09-21 03:45
What made you decide it is a synth problem and not a bug with FreeBSD-CURRENT?

**Comment by mjoras** [comment] 2017-09-21 03:50
Nothing particularly, I suppose. Is it not likely the Synth has a resource leak?

**Comment by jrmarino** [comment] 2017-09-21 03:52
Not, it is not likely.
It's more likely that a bleeding edge developmental version of FreeBSD has a bug in it, especially given that nobody has reported anything like this under the previous 2 years.  Synth is also used to build 24,000 port runs on DragonFly continuously without any kind of "resource issue" in the last 2 years.

**Comment by mjoras** [comment] 2017-09-21 04:00
It's worth noting, I think, that the particular error happens under a `_PTHREADS_INVARIANTS` ifdef, so it is an extra check presumably to help people from writing threaded code that doesn't clean up its locks. It's possible it is a FreeBSD libthr bug, I will look into it.

**Comment by mjoras** [comment] 2017-09-21 04:14
It is also perhaps worth noting that the DragonFly version of libthr does not have this particular seatbelt:
https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/lib/libthread_xu/thread/thr_exit.c#L127-L162
vs
https://github.com/freebsd/freebsd/blob/master/lib/libthr/thread/thr_exit.c#L277-L324

So if it were a Synth issue it seems that DragonFly would not crash under these conditions.

**Comment by jrmarino** [comment] 2017-09-21 12:00
It is also worth noting that Synth is written in Ada, which means the interface with the threads library is indirect and controlled by the compiler.

Ada's concurrency is accomplished through _tasks_.  The compiler internally translates tasking to the local equivalent, which in the case of FreeBSD and DragonFly are libpthread interfaces.  So if this is caused by the application, the error is in the compiler itself.

so the reason it doesn't happen on FreeBSD 11 is because libthr.so isn't compiled with _PTHREADS_INVARIANTS defined ?

**Comment by mjoras** [comment] 2017-09-27 05:24
Right, forgive me I didn't know much about Ada but now understand. It does seem likely this is a bad interaction with the Ada compiler/runtime and libthr.

As for _PTHREADS_INVARIANTS, it seems that it's been around since 2007, and this particular check has been around since 2010, so that doesn't explain anything unfortunately :(. I think this is most likely a regression, perhaps in the compiler, or the runtime, or libthr itself. The last seems sort of unlikely. I can try to see how far back in CURRENT I can reproduce it...

**Comment by jrmarino** [comment] 2017-09-27 16:12
My question is whether _PTHREADS_INVARIANTS is defined for releases.
It might have been present since 2010, but if it's only defined for -CURRENT, you'd only see the fatal warning on FreeBSD dev branches.  I could look it up myself but was just wondering offhand if this code is effectively missing from releases.  If I had to guess, I would say it is, but at this point it's just a guess.

**Comment by jrmarino** [comment] 2017-10-17 12:56
btw, I generated a new bootstrap compiler so that gcc6-aux builds on FreeBSD-CURRENT again.   I guess you were using synth built for FreeBSD 11.  I doubt having a "native" built synth on -CURRENT would make a difference on this issue, but maybe so.

**Comment by jrmarino** [comment] 2018-12-03 16:29
closing due to no active > 1 year.

**Closed** 2018-12-03 16:30 UTC
