### ISSUE TITLE
<OPTIONS_NAME>_UNSET in make.conf ignored by synth and other remarks

### ISSUE THREAD

**Issue by cmanv** [jrmarino/synth#9] opened 2016-01-17 01:08 UTC
This report concerns version 0.98_2 from the FreeBSD ports. (On 10.2-STABLE)

~~1- When /var/db/ports is not populated, synth does not take account of the UNSET options from /etc/make.conf
For example, lang_gcc_UNSET= JAVA  was not picked up by synth. I had to do a 'make config' prior to the build.~~

[ Update:
I may have misread the man page here:
 _If it exits, (sic) the builder's /etc/make.conf will be appended with the contents of this file._

I just realized that the builder's /etc/make.conf may not be the host's /etc/make.conf. And just using the profile's _LiveSystem-make.conf_ as indicated solves this issue.
]

2- I observed that 'load' stays at 0% in the curses display throughout the build. (btw this display is really a nice touch)

3- IMO, it would be better to have a combination of keys (Ctrl+Esc or Alt+Esc) to trigger a "graceful exit" as it is currently very easy to mistakenly trigger such an exit. (It happened to me.  Twice.)

**Comment by jrmarino** [comment] 2016-01-17 08:04
I don't know what to say about the load.  Nobody else is experiencing that.  What does "uptime" show?

**Comment by cmanv** [comment] 2016-01-17 14:42
Uptime? The uptime of my laptop was in the hours range. If you mean the duration of the build, it's printing the correct value. As an example, I'm running 3 concurrent builds here. 'top' shows a load over 6, yet the load in the display stays at 0.00. All other indicators seem fine (including swap usage when it occurs)

![x](https://cloud.githubusercontent.com/assets/16738761/12377963/1a50b8ea-bcfd-11e5-8a8a-fccfcbfc81d5.png)

**Comment by jrmarino** [comment] 2016-01-17 14:44
i meant the output of the uptime command, e.g. "/usr/bin/uptime"

**Comment by cmanv** [comment] 2016-01-17 14:45
Here you go:
 9:45  up 36 mins, 2 users, load averages: 7,07 7,10 6,06

**Comment by jrmarino** [comment] 2016-01-17 14:47
okay, it's the decimal separator.  Synth is looking for "." not commas.  Since uptime is locale sensitive, it needs LANG set to "C".

In the meantime, you can launch synth with "env LANG=C synth ...." and it should work

**Comment by cmanv** [comment] 2016-01-17 14:49
Ok, I see the load now. Thanks!

**Comment by jrmarino** [comment] 2016-01-17 14:55
actually it gets the value from "/sbin/sysctl vm.loadavg" but the cause of the issue is the same I suspect.

**Comment by jrmarino** [comment] 2016-01-17 15:23
as a side note, "sysctl vm.loadavg" is only locale sensitive on FreeBSD.  On DragonFly, it always uses the dot as the decimal separator.

**Comment by jrmarino** [comment] 2016-01-17 15:41
should be fixed here: 90bac4f1f7f85d75f9f17446b7ac2c8c812d2e82
I'm pushing 0.98_3 to freebsd soon, which will have this fix.

**Closed by jrmarino** 2016-01-17 15:41 UTC
